### ISSUE TITLE
Trim down Bootstrap

### ISSUE THREAD

**Issue by Darthagnon** [Darthagnon/hugo-easy-gallery#1]
Bootstrap is required for the image grid, but is otherwise overkill. It needs trimming down to the bare minimum required for the responsive square grid.

Probably should also be updated from v3.7.7, which I lifted from [Beautiful Hugo](https://github.com/halogenica/beautifulhugo)

**Comment by Darthagnon** [comment]
@nunocoracao, would you be interested in helping with this issue?

Any advice you might have would be appreciated, since you know CSS frameworks much better than I

**Comment by Darthagnon** [comment]
Working on it in this branch: https://github.com/Darthagnon/hugo-easy-gallery/tree/remove-bootstrap

**Comment by Darthagnon** [comment]
Merged changes, fixed. Will close soon, after my friend nunocoracao has had a chance to look

**Comment by nunocoracao** [comment]
@Darthagnon sorry, a little lost here... that branch does not exist anymore and there is no PR to look at... which changes do you want me to look at?

**Comment by nunocoracao** [comment]
Until you get back to me, you can consider using NPM to manage your dependencies. That way you can setup GitHub dependabot to generate PRs bumping the versions every time there is an update. That plus GitHub actions for automation can make your life easier. 

You can check [Blowfisth](https://github.com/nunocoracao/blowfish) for a IRL example of what I am saying.

**Comment by Darthagnon** [comment]
My bad; I must have been programming this one late at night and forgot I deleted the branch - I added Bootstrap temporarily in 8f8c736823bc450e01b7273e822d3be02bf89f4e and removed it (after isolating what was needed) in f769bdf415dad430d9ecce36e4ac378b411a2041 and forwards. It seems to work in production, so unless anything turns up, seems to be solved.

**Comment by Darthagnon** [comment]
Thank you for your suggestions, @nunocoracao! I'll try implementing that where I need updated dependencies, though for the moment, this repo's only dependency is Photoswipe, intentionally kept on an older version for compatibility.
