### ISSUE TITLE
{{< load-photoswipe >}} does not work

### ISSUE THREAD

**Issue by condio** [Darthagnon/hugo-easy-gallery#5]
Maybe it's just my primary theme (papermod), but I am struggling to get PhotoSwipe to work on my site.

I installed this theme and linked it, and I even manually added the necessary files to my site.

{{< gallery >}} works fine and I can call individual figures within.

{{< load-photoswipe >}} will not work and my gallery images only load in full screen. Strangely everything works but this and the thumbnail size.

Is this currently broken or am I possibly doing something wrong? Thanks for your help.

**Comment by condio** [comment]
Giving up on this. The example site doesn't even work for me. Must be something on my end if everyone else is fine using the releases.

**Comment by RoneoOrg** [comment]
I add a similar issue with the Papermod theme: I had to remove the "cover" from the Front matter.

In details, I deleted the following lines:

```
cover:
    image: "img/25.jpg"
    alt: "an abstract paint"
```

You can also use the [`cover: hidden` feature](https://github.com/adityatelange/hugo-PaperMod/issues/818)

@condio
